services:
  mongodb:
    image: mongo:6.0
    container_name: boardgames_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=boardgames_tp3

volumes:
  mongo_data: